Repository eclipse-elk/elk, pull requests merged in 2020-02, with the labels that each got.

#484 Issue #483: RectPacking: Initialize values with MIN_VALUE instead of -Infinity.
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/RectPackingLayoutProvider.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/firstiteration/ScaleMeasureFilter.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/seconditeration/Compaction.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/seconditeration/RowFillingAndCompaction.java
Labels: bug

#493 fix of potential NPE in 'ElkGraphAdapters'
  plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/adapters/ElkGraphAdapters.java
Labels: bug

#498 Change how layout algorithms are resolved
  plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/data/LayoutAlgorithmResolver.java
  test/org.eclipse.elk.core.test/src/org/eclipse/elk/core/RecursiveGraphLayoutEngineTest.java
Labels: enhancement, tests

#499 Reworked rect packing
  plugins/org.eclipse.elk.alg.packing.rectangles/docs/packingstrategy.md
  plugins/org.eclipse.elk.alg.packing.rectangles/docs/rectpacking.md
  plugins/org.eclipse.elk.alg.packing.rectangles/images/options/expand_to_aspect_ratio.png
  plugins/org.eclipse.elk.alg.packing.rectangles/images/options/initial_placement.png
  plugins/org.eclipse.elk.alg.packing.rectangles/images/options/node_expansion.png
  plugins/org.eclipse.elk.alg.packing.rectangles/images/options/row_compaction.png
  plugins/org.eclipse.elk.alg.packing.rectangles/images/options/strategy_areadriven.png
  plugins/org.eclipse.elk.alg.packing.rectangles/images/options/strategy_aspectratiodriven.png
  plugins/org.eclipse.elk.alg.packing.rectangles/images/options/strategy_maxscaledriven.png
  plugins/org.eclipse.elk.alg.packing.rectangles/images/options/width_approximation.png
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/RectPacking.melk
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/RectPackingLayoutProvider.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/firstiteration/AreaApproximation.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/firstiteration/AreaFilter.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/firstiteration/AspectRatioFilter.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/firstiteration/BestCandidateFilter.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/firstiteration/Calculations.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/firstiteration/ScaleMeasureFilter.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/seconditeration/Compaction.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/seconditeration/InitialPlacement.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/seconditeration/RectangleExpansion.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/seconditeration/RowFilling.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/seconditeration/RowFillingAndCompaction.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/specialcase/ExpandNodesSpecialCase.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/specialcase/SpecialCaseFeasibility.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/specialcase/SpecialCasePlacer.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/util/Block.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/util/BlockRow.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/util/BlockStack.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/util/DrawingData.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/util/DrawingDataDescriptor.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/util/DrawingUtil.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/util/PackingStrategy.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/util/RectRow.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/util/RectStack.java
  test/org.eclipse.elk.alg.test/META-INF/MANIFEST.MF
  test/org.eclipse.elk.alg.test/src/org/eclipse/elk/alg/test/PlainJavaInitialization.java
Labels: enhancement

#505 Fixed problems with rect packing algorithm
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/RectPacking.melk
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/RectPackingLayoutProvider.java
  plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/seconditeration/Compaction.java
Labels: bug
