Repository eclipse-elk/elk, pull requests merged in 2020-07, with the labels that each got.

#655 [PR] Layered: Fix layer constraint processing. #623
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/IntermediateProcessorStrategy.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/LayerConstraintPostprocessor.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/LayerConstraintPreprocessor.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/LayerConstraintProcessor.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/InternalProperties.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p2layers/CoffmanGrahamLayerer.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p2layers/InteractiveLayerer.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p2layers/LongestPathLayerer.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p2layers/MinWidthLayerer.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p2layers/NetworkSimplexLayerer.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p2layers/StretchWidthLayerer.java
  test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/LayerConstraintProcessorTest.java
Labels: alg-layered, bug

#658 [PR] Removed outdated xtend build workarounds
  plugins/org.eclipse.elk.alg.graphviz.layouter/pom.xml
  plugins/org.eclipse.elk.alg.mrtree/pom.xml
  plugins/org.eclipse.elk.alg.spore/pom.xml
Labels: build

#640 [PR] Preserve node and edge order
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/GraphConfigurator.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/components/ComponentsProcessor.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/components/SimpleRowGraphPlacer.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphImporter.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/IntermediateProcessorStrategy.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/SortByInputModelProcessor.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/preserveorder/ModelOrderNodeComparator.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/preserveorder/ModelOrderPortComparator.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/InternalProperties.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/OrderingStrategy.java
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/LayerSweepCrossingMinimizer.java
  test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/SortByInputModelProcessorTest.java
Labels: alg-layered, new feature

#662 Don't set edge placement during JsonImport if undefined
  plugins/org.eclipse.elk.graph.json/src/org/eclipse/elk/graph/json/JsonImporter.xtend
Labels: core

#669 [PR] (2) Removed outdated xtend build workarounds
  plugins/org.eclipse.elk.alg.common/pom.xml
  plugins/org.eclipse.elk.alg.disco/pom.xml
  plugins/org.eclipse.elk.alg.force/pom.xml
  plugins/org.eclipse.elk.alg.layered/pom.xml
  plugins/org.eclipse.elk.alg.radial/pom.xml
  plugins/org.eclipse.elk.alg.rectpacking/pom.xml
  plugins/org.eclipse.elk.conn.gmf/pom.xml
  plugins/org.eclipse.elk.core/pom.xml
Labels: build, chore

#648 [PR] [WIP] Docs: Started writing release notes.
  docs/content/downloads/releasenotes/release-0.7.0.md
Labels: website

#677 [PR] Download management script
  build/releng/manage.py
Labels: build, chore
