Repository eclipse-elk/elk, pull requests merged in 2022-11, with the labels that each got.

#892 Created blog post about libavoid
  docs/content/blog/_index.md
  docs/content/blog/posts/2022/22-08-31-rectpacking.md
  docs/content/blog/posts/2022/22-11-17-libavoid.md
Labels: website

#888 Fix ClassCastException during Layout
  plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/LayerSweepCrossingMinimizer.java
Labels: alg-layered

#805 Verify layout of example models does not raise an exception
  test/org.eclipse.elk.shared.test/src/org/eclipse/elk/shared/test/ElkLiveExamplesTest.java
Labels: tests, alg
