Repository eclipse-elk/elk, pull requests merged in 2025-05, with the labels that each got.

#1087 fixes padding issue of box algorithm
  plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/BoxLayoutProvider.java
Labels: alg

#1129 libavoidCancelRouting: Add a method that enables canceling of a started layout operation with libavoid
  plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/LibavoidLayoutProvider.java
  plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/server/LibavoidServer.java
Labels: enhancement, alg-libavoid

#1144 Add the fixed integer size approximator
  plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/Core.melk
  plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/RecursiveGraphLayoutEngine.java
  plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/options/ITopdownSizeApproximator.java
  plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/options/TopdownSizeApproximator.java
  plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/options/TopdownSizeApproximatorUtil.java
Labels: new feature, alg
